#ifndef BKIT_PROTOCOL_H
#define BKIT_PROTOCOL_H

#include "sensor.pb.h" // Generated by Nanopb
#include <stdint.h>
#include <stdbool.h>

// Constants
#define BKIT_START_BYTE 0x7E
#define MAX_PAYLOAD_SIZE 64 // Adjust based on your Protobuf size

// Struct for the Protocol Header
typedef struct {
    uint16_t length;
    uint16_t crc;
    uint8_t flags;
} bkit_header_t;

// API Functions [cite: 125]
bool bkit_send_message(const SensorData* data);
bool bkit_receive_message(SensorData* data);

#endif