/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SENSOR_PB_H_INCLUDED
#define PB_SENSOR_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SensorData {
    uint32_t sensor_id;
    float sensor_value;
    uint64_t timestamp;
} SensorData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SensorData_init_default                  {0, 0, 0}
#define SensorData_init_zero                     {0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SensorData_sensor_id_tag                 1
#define SensorData_sensor_value_tag              2
#define SensorData_timestamp_tag                 3

/* Struct field encoding specification for nanopb */
#define SensorData_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    sensor_value,      2) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         3)
#define SensorData_CALLBACK NULL
#define SensorData_DEFAULT NULL

extern const pb_msgdesc_t SensorData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SensorData_fields &SensorData_msg

/* Maximum encoded size of messages (where known) */
#define SENSOR_PB_H_MAX_SIZE                     SensorData_size
#define SensorData_size                          22

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
